---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# fortress-suburbia

<!-- badges: start -->
<!-- badges: end -->

The Fortress Suburbia GitHub project represents all of my work towards an undergraduate thesis part of the LIFESCI 4C12 course under the supervision of Dr. Páez at McMaster University. 

The goal of the thesis is to examine how street patterns were designed in American suburbia following the Second World War, especially with regards to racial segregation through physical community design.

This GitHub project includes files that are part of my final work, such as the `Introduction and Liteature Review.Rmd`, but also work that represents my learning process. These files, such as `my-first-notebook.Rmd`, show my progress in learning skills to use in this thesis project, such as collecting data for mapping cities and neighbourhoods, as seen in the `plots` folder.

The thesis project is expected to be completed in April 2025. In the meantime, however, you can view all the current files for this project on GitHub, as well as the edit history in the Commit Log.

Thank you for your interest in my project and I hope you learn something new!

Amanda