---
title: "City Data"
output: html_notebook
---

## Selected Cities

The following cities' datas will be used for the Fortress Suburbia project:

- Phoenix, Arizona (metropolitan population = ~5.1 million) [part 1 done]
- Tampa, Florida (metropolitan population = ~) [part 1 done]
- Atlanta, Georgia (metropolitan population = ~6.2 million) [NOT done]
- Nashville, Tennessee (metropolitan population = ~2.1 million) [part 1 done]
- Houston, Texas (metropolitan population = ~6.8 million) [part 1 done]

These selected cities:

- Are all located in the Sun Belt of the United States.
- All have metropolitan populations of >2 million people as of 2024.
- All have experienced significant urban sprawl in the last few decades.

The data (streets and other amenities) for these cities will be downloaded and saved to the `fortress-suburbia/data-raw` folder. The chunks of code for running this data will be below but hidden in .html view. To access the code, open the `City Data.Rmd` and individual city files.

